"""
Production
Django settings for warehouse project.
Generated by 'django-admin startproject' using Django 1.8.5.
"""

from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4k6irf(q-=4key-p+)ur6m#2a+t+0%+1gfg4ps#8gwv9g-jf51'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

import dj_database_url

ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': dj_database_url.config()
}

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
